#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Time-Local
version:      1.05
version_from: lib/Time/Local.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_04
