#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Time-Local
version:      1.07_93
version_from: lib/Time/Local.pm
installdirs:  perl
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
